// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSO1Ebd6b0rZgRvQqlVvHHDkTPlvtN5Q',
    appId: '1:600982820933:web:9d1e5ee3285892f230eb2c',
    messagingSenderId: '600982820933',
    projectId: 'fruitshub-1b658',
    authDomain: 'fruitshub-1b658.firebaseapp.com',
    storageBucket: 'fruitshub-1b658.firebasestorage.app',
    measurementId: 'G-PRER0SCRE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZnYOAPDXBbmf2STrg9bQSYpwzTGdgI6E',
    appId: '1:600982820933:android:efec8ed1d4569fc730eb2c',
    messagingSenderId: '600982820933',
    projectId: 'fruitshub-1b658',
    storageBucket: 'fruitshub-1b658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3_DudBZ-PH5e_-_FMp21swu8jTuu1OWk',
    appId: '1:600982820933:ios:d20c0d270af4670530eb2c',
    messagingSenderId: '600982820933',
    projectId: 'fruitshub-1b658',
    storageBucket: 'fruitshub-1b658.firebasestorage.app',
    iosBundleId: 'com.example.furitsapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3_DudBZ-PH5e_-_FMp21swu8jTuu1OWk',
    appId: '1:600982820933:ios:d20c0d270af4670530eb2c',
    messagingSenderId: '600982820933',
    projectId: 'fruitshub-1b658',
    storageBucket: 'fruitshub-1b658.firebasestorage.app',
    iosBundleId: 'com.example.furitsapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRSO1Ebd6b0rZgRvQqlVvHHDkTPlvtN5Q',
    appId: '1:600982820933:web:dd813751f9dbb11630eb2c',
    messagingSenderId: '600982820933',
    projectId: 'fruitshub-1b658',
    authDomain: 'fruitshub-1b658.firebaseapp.com',
    storageBucket: 'fruitshub-1b658.firebasestorage.app',
    measurementId: 'G-J8L2RK7YV4',
  );
}
